version: "3"
services:
    api:
        env_file:
            - .env
        build: .
        restart: always
        ports:
            - "8000:8000"
        networks:
            - anvisa_service
        depends_on:
            - cache
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
        networks:
            - anvisa_service
volumes:
    cache:
        driver: local
networks:
    anvisa_service:
        name: anvisa_service
